services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    restart: unless-stopped
    volumes:
      - .:/usr/src/app
    ports:
      - ${PORT}:${PORT}
    environment:
      APP_ENV: ${APP_ENV}
      PORT: ${PORT}
    develop:
      watch:
        - action: sync+restart
          path: ./internal/
          target: /usr/src/app 
