// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"database/sql"
)

type Payment struct {
	CorrelationID interface{}
	Amount        interface{}
	Timestamp     sql.NullTime
}
