// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package repository

import (
	"context"
	"database/sql"
)

const createPaymentRecord = `-- name: CreatePaymentRecord :one
INSERT INTO PAYMENTS (
  CORRELATION_ID, AMOUNT, TIMESTAMP, PROCESSOR
) VALUES (
  ?, ?, ?, ?
)
RETURNING correlation_id, amount, timestamp, processor
`

type CreatePaymentRecordParams struct {
	CorrelationID interface{}
	Amount        interface{}
	Timestamp     sql.NullTime
	Processor     interface{}
}

func (q *Queries) CreatePaymentRecord(ctx context.Context, arg CreatePaymentRecordParams) (Payment, error) {
	row := q.db.QueryRowContext(ctx, createPaymentRecord,
		arg.CorrelationID,
		arg.Amount,
		arg.Timestamp,
		arg.Processor,
	)
	var i Payment
	err := row.Scan(
		&i.CorrelationID,
		&i.Amount,
		&i.Timestamp,
		&i.Processor,
	)
	return i, err
}

const getAllPayments = `-- name: GetAllPayments :many
SELECT CORRELATION_ID, AMOUNT, TIMESTAMP FROM PAYMENTS
ORDER BY TIMESTAMP DESC
`

type GetAllPaymentsRow struct {
	CorrelationID interface{}
	Amount        interface{}
	Timestamp     sql.NullTime
}

func (q *Queries) GetAllPayments(ctx context.Context) ([]GetAllPaymentsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllPayments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllPaymentsRow
	for rows.Next() {
		var i GetAllPaymentsRow
		if err := rows.Scan(&i.CorrelationID, &i.Amount, &i.Timestamp); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPaymentByCorrelationId = `-- name: GetPaymentByCorrelationId :one
SELECT CORRELATION_ID, AMOUNT, TIMESTAMP FROM PAYMENTS
WHERE CORRELATION_ID = ? LIMIT 1
`

type GetPaymentByCorrelationIdRow struct {
	CorrelationID interface{}
	Amount        interface{}
	Timestamp     sql.NullTime
}

func (q *Queries) GetPaymentByCorrelationId(ctx context.Context, correlationID interface{}) (GetPaymentByCorrelationIdRow, error) {
	row := q.db.QueryRowContext(ctx, getPaymentByCorrelationId, correlationID)
	var i GetPaymentByCorrelationIdRow
	err := row.Scan(&i.CorrelationID, &i.Amount, &i.Timestamp)
	return i, err
}

const getPaymentsByInterval = `-- name: GetPaymentsByInterval :many
SELECT CORRELATION_ID, AMOUNT, TIMESTAMP FROM PAYMENTS
WHERE TIMESTAMP BETWEEN ? AND ?
ORDER BY TIMESTAMP DESC
`

type GetPaymentsByIntervalParams struct {
	FromTimestamp sql.NullTime
	ToTimestamp   sql.NullTime
}

type GetPaymentsByIntervalRow struct {
	CorrelationID interface{}
	Amount        interface{}
	Timestamp     sql.NullTime
}

func (q *Queries) GetPaymentsByInterval(ctx context.Context, arg GetPaymentsByIntervalParams) ([]GetPaymentsByIntervalRow, error) {
	rows, err := q.db.QueryContext(ctx, getPaymentsByInterval, arg.FromTimestamp, arg.ToTimestamp)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPaymentsByIntervalRow
	for rows.Next() {
		var i GetPaymentsByIntervalRow
		if err := rows.Scan(&i.CorrelationID, &i.Amount, &i.Timestamp); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const summarizePaymentsByInterval = `-- name: SummarizePaymentsByInterval :many
SELECT SUM(AMOUNT), PROCESSOR FROM PAYMENTS
WHERE TIMESTAMP BETWEEN ? AND ?
GROUP BY PROCESSOR
`

type SummarizePaymentsByIntervalParams struct {
	FromTimestamp sql.NullTime
	ToTimestamp   sql.NullTime
}

type SummarizePaymentsByIntervalRow struct {
	Sum       sql.NullFloat64
	Processor interface{}
}

func (q *Queries) SummarizePaymentsByInterval(ctx context.Context, arg SummarizePaymentsByIntervalParams) ([]SummarizePaymentsByIntervalRow, error) {
	rows, err := q.db.QueryContext(ctx, summarizePaymentsByInterval, arg.FromTimestamp, arg.ToTimestamp)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SummarizePaymentsByIntervalRow
	for rows.Next() {
		var i SummarizePaymentsByIntervalRow
		if err := rows.Scan(&i.Sum, &i.Processor); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
