-- name: GetPaymentByCorrelationId :one
SELECT CORRELATION_ID, AMOUNT, TIMESTAMP FROM PAYMENTS
WHERE CORRELATION_ID = ? LIMIT 1;

-- name: GetAllPayments :many
SELECT CORRELATION_ID, AMOUNT, TIMESTAMP FROM PAYMENTS
ORDER BY TIMESTAMP DESC;

-- name: GetPaymentsByInterval :many
SELECT CORRELATION_ID, AMOUNT, TIMESTAMP FROM PAYMENTS
WHERE TIMESTAMP BETWEEN ? AND ?
ORDER BY TIMESTAMP DESC;

-- name: CreatePaymentRecord :one
INSERT INTO PAYMENTS (
  CORRELATION_ID, AMOUNT, TIMESTAMP
) VALUES (
  ?, ?, ?
)
RETURNING *;
